name: "Build Docker Image"
on:
  push:
    branches:
      - master
      - test
  pull_request:

jobs:
  Pipeline:
    runs-on: ubuntu-16.04
    container: docker

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      run: docker build --tag meli-challenge .
